name: module3_task2
on:
  schedule:
    - cron: "0 0 * * *"
  push:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Run the setup
        working-directory: module3_task2
        run: sudo ./setup.sh
      - name: Build the site
        working-directory: module3_task2
        run: make build
      - name: Make a new post
        working-directory: module3_task2
        run: make post POST_NAME=kanyewestlover911 POST_TITLE="find god"
      - name: Find some help
        working-directory: module3_task2
        run: make help
      - name: Clean the site
        working-directory: module3_task2
        run: make clean
      - name: Make the zip files
        working-directory: module3_task2
        run: make package
