name: module4_task0
on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened]
  push:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    container: 
      image: golang:1.15.8-buster
      ports:
        - 80
      volumes:
        - my_docker_volume:/volume_mount
      options:
        --cpus 1
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Check for go version
        run: ls
