name: module4_task0
on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened]
  push:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Clone the repo
        uses: actions/checkout@v3
      - name: Test docker
        run: | 
          docker container create -it --name mycontainer golang:1.15.8-buster
          docker run --name mycontainer ls
        
