name: module4_task0
on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:
    types: [opened, reopened]
  push:
jobs:
  deploy:
    runs-on: ubuntu-18.04
    container:
      image: docker/Dockerfile
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check docker version
        run: ls
